Lecture04
tomi0118/practice pull request #7
Opened 2024-02-13 05:51 UTC by tomi0118

第４回の課題を提出します。
ご確認の程宜しくお願いいたします。

2024-02-13 06:06 UTC, MasatoshiMizumoto requested changes
第4回の課題報告はOKなのですが、他で訂正いただきたいところがありますので、ご対応お願いします！！

2024-02-13 06:06 UTC, MasatoshiMizumoto commented on image/.DS_Store
このファイルはGitに含めないようにお願いします！

2024-02-13 06:06 UTC, MasatoshiMizumoto commented on lecture03.md
行を消す変更が加わってますが、問題ないでしょうか？

2024-02-13 06:07 UTC, MasatoshiMizumoto commented on lecture03.md
そもそもこのファイルは変更したかったファイルですかね？
第4回のブランチを作る前にやるべきだったことが抜けているなど、手順漏れがあった気がします！

2024-02-13 06:18 UTC, tomi0118 commented on image/.DS_Store
ファイルを削除しました。第３回の時も同じファイルがgitに含まれてしまいました。次回の課題提出までに含まれないように設定します。

2024-02-13 12:41 UTC, tomi0118 commented on lecture03.md
このファイルは第３回の課題のファイルなので変更を必要としないファイルです。
ただ第４回の課題をするにあたって、少し行の改行や削除をしてしまいました。それをファイルのステージングをする際にgit add .のコマンドで全てのファイルをステージングしてしまったことが原因だと思ったのですが、違いますかね？

2024-02-18 12:54 UTC, tomi0118 commented on lecture03.md
githubのハンズオンを見返していたら、今までpullせずローカルPCにメインブランチの更新をしておらず、また不要になったブランチを削除していないことに気づきました。この作業って今からでもした方がいい良いのでしょうか？ただ、今まで課題毎にリモートレポジトリをローカルリポジトリにクローンしていたため、pullは不要だと思うのですが
どうすればどのようにすればよいでしょうか？

2024-02-19 13:12 UTC, MasatoshiMizumoto commented on lecture03.md
どんなデータにしたいかによるので、今のままで良いならそのままでいいと思いますよ！

2024-02-19 13:31 UTC, tomi0118 commented on lecture03.md
確認いただきありがとうございます。特に違和感はないのでこのままにしておきます。

2024-02-19 15:31 UTC, MasatoshiMizumoto approved these changes
LGTMです！

2024-02-21 13:32 UTC, merged